namespace ijs; 

public readonly struct ElementsName {
    public readonly string jpn;
    //public readonly string eng;

    public ElementsName(string jpn) {
        this.jpn = jpn;
    }

    public override string ToString() {
        return $"{jpn}";
    }

    public static ElementsName FromElementsId(ElementsId elementsId) {
        var lv = $" レベル{elementsId.level.ToEnumString()}";
        return elementsId.code switch {
            ElementsCode._1T => new ElementsName("1回転トウループ"),
            ElementsCode._1S => new ElementsName("1回転サルコウ"),
            ElementsCode._1Lo => new ElementsName("1回転ループ"),
            ElementsCode._1Eu => new ElementsName("オイラー"),
            ElementsCode._1F => new ElementsName("1回転フリップ"),
            ElementsCode._1Lz => new ElementsName("1回転ルッツ"),
            ElementsCode._1A => new ElementsName("1回転アクセル"),
            ElementsCode._2T => new ElementsName("2回転トウループ"),
            ElementsCode._2S => new ElementsName("2回転サルコウ"),
            ElementsCode._2Lo => new ElementsName("2回転ループ"),
            ElementsCode._2F => new ElementsName("2回転フリップ"),
            ElementsCode._2Lz => new ElementsName("2回転ルッツ"),
            ElementsCode._2A => new ElementsName("2回転アクセル"),
            ElementsCode._3T => new ElementsName("3回転トウループ"),
            ElementsCode._3S => new ElementsName("3回転サルコウ"),
            ElementsCode._3Lo => new ElementsName("3回転ループ"),
            ElementsCode._3F => new ElementsName("3回転フリップ"),
            ElementsCode._3Lz => new ElementsName("3回転ルッツ"),
            ElementsCode._3A => new ElementsName("3回転アクセル"),
            ElementsCode._4T => new ElementsName("4回転トウループ"),
            ElementsCode._4S => new ElementsName("4回転サルコウ"),
            ElementsCode._4Lo => new ElementsName("4回転ループ"),
            ElementsCode._4F => new ElementsName("4回転フリップ"),
            ElementsCode._4Lz => new ElementsName("4回転ルッツ"),
            ElementsCode._4A => new ElementsName("4回転アクセル"),
            ElementsCode.USp => new ElementsName("アップライト"),
            ElementsCode.LSp => new ElementsName("レイバック"),
            ElementsCode.CSp => new ElementsName("キャメル"),
            ElementsCode.SSp => new ElementsName("シット"),
            ElementsCode.FUSp => new ElementsName("フライングアップライト"),
            ElementsCode.FLSp => new ElementsName("フライングレイバック"),
            ElementsCode.FCSp => new ElementsName("フライングキャメル"),
            ElementsCode.FSSp => new ElementsName("フライングシット"),
            ElementsCode.FCUSp => new ElementsName("フライング足替えアップライト"),
            ElementsCode.FCLSp => new ElementsName("フライング足替えレイバック"),
            ElementsCode.FCCSp => new ElementsName("フライング足替えキャメル"),
            ElementsCode.FCSSp => new ElementsName("フライング足替えシット"),
            ElementsCode.FCoSp => new ElementsName("フライングコンビネーション"),
            ElementsCode.FCCoSp => new ElementsName("フライング足換えコンビネーション"),
            ElementsCode.StSq => new ElementsName($"ステップシークエンス{lv}"),
            ElementsCode.ChSq => new ElementsName($"コレオグラフィックシークエンス{lv}"),
            ElementsCode._1Li => new ElementsName($"グループ1{lv}"),
            ElementsCode._2Li => new ElementsName($"グループ2{lv}"),
            ElementsCode._3Li => new ElementsName($"グループ3{lv}"),
            ElementsCode._4Li => new ElementsName($"グループ4{lv}"),
            ElementsCode._5TLi => new ElementsName($"グループ5 トゥラッソー{lv}"),
            ElementsCode._5SLi => new ElementsName($"グループ5 ステップインラッソー{lv}"),
            ElementsCode._5BLi => new ElementsName($"グループ5 バックワードラッソー{lv}"),
            ElementsCode._5ALi => new ElementsName($"グループ5 アクセルラッソー{lv}"),
            ElementsCode._5RLi => new ElementsName($"グループ5 リバースラッソー{lv}"),
            ElementsCode._1Tw => new ElementsName($"1回転ツイストリフト{lv}"),
            ElementsCode._2Tw => new ElementsName($"2回転ツイストリフト{lv}"),
            ElementsCode._3Tw => new ElementsName($"3回転ツイストリフト{lv}"),
            ElementsCode._4Tw => new ElementsName($"4回転ツイストリフト{lv}"),
            ElementsCode._1TTh => new ElementsName("1回転トウループ"),
            ElementsCode._1STh => new ElementsName("1回転サルコウ"),
            ElementsCode._1LoTh => new ElementsName("1回転ループ"),
            ElementsCode._1FTh => new ElementsName("1回転フリップ"),
            ElementsCode._1LzTh => new ElementsName("1回転ルッツ"),
            ElementsCode._1ATh => new ElementsName("1回転アクセル"),
            ElementsCode._2TTh => new ElementsName("2回転トウループ"),
            ElementsCode._2STh => new ElementsName("2回転サルコウ"),
            ElementsCode._2LoTh => new ElementsName("2回転ループ"),
            ElementsCode._2FTh => new ElementsName("2回転フリップ"),
            ElementsCode._2LzTh => new ElementsName("2回転ルッツ"),
            ElementsCode._2ATh => new ElementsName("2回転アクセル"),
            ElementsCode._3TTh => new ElementsName("3回転トウループ"),
            ElementsCode._3STh => new ElementsName("3回転サルコウ"),
            ElementsCode._3LoTh => new ElementsName("3回転ループ"),
            ElementsCode._3FTh => new ElementsName("3回転フリップ"),
            ElementsCode._3LzTh => new ElementsName("3回転ルッツ"),
            ElementsCode._3ATh => new ElementsName("3回転アクセル"),
            ElementsCode._4TTh => new ElementsName("4回転トウループ"),
            ElementsCode._4STh => new ElementsName("4回転サルコウ"),
            ElementsCode._4LoTh => new ElementsName("4回転ループ"),
            ElementsCode._4FTh => new ElementsName("4回転フリップ"),
            ElementsCode._4LzTh => new ElementsName("4回転ルッツ"),
            ElementsCode.FiDs => new ElementsName($"フォアイン{lv}"),
            ElementsCode.BiDs => new ElementsName($"バックイン{lv}"),
            ElementsCode.FoDs => new ElementsName($"フォアアウト{lv}"),
            ElementsCode.BoDs => new ElementsName($"バックアウト{lv}"),
            ElementsCode.PiF => new ElementsName("ピボットフィギュア"),
            ElementsCode.PSp => new ElementsName($"ペア{lv}"),
            ElementsCode.PCoSp => new ElementsName($"ペアコンビネーション{lv}"),
            ElementsCode._1BL => new ElementsName($"ブルース第1シークエンス{lv}"),
            ElementsCode._2BL => new ElementsName($"ブルース第2シークエンス{lv}"),
            ElementsCode._1MN => new ElementsName($"ミッドナイトブルース第1シークエンス{lv}"),
            ElementsCode.Sp => new ElementsName($"スピン{lv}"),
            ElementsCode.CoSp => new ElementsName($"コンビネーションスピン{lv}"),
            ElementsCode.StaLi => new ElementsName($"ステーショナリーリフト{lv}"),
            ElementsCode.SlLi => new ElementsName($"ストレートラインリフト{lv}"),
            ElementsCode.CuLi => new ElementsName($"カーブリフト{lv}"),
            ElementsCode.RoLi => new ElementsName($"ローテーショナルリフト{lv}"),
            ElementsCode.STw => new ElementsName($"ツイズル・セット{lv}"),
            ElementsCode.PSt => new ElementsName($"パーシャルステップシークエンス{lv}"),
            ElementsCode.MiSt => new ElementsName($"ミッドライン{lv}"),
            ElementsCode.CiSt => new ElementsName($"サーキュラー{lv}"),
            ElementsCode.SeSt => new ElementsName($"サーペンタイン{lv}"),
            ElementsCode.NtMiSt => new ElementsName($"非接触ミッドライン{lv}"),
            ElementsCode.NtDiSt => new ElementsName($"非接触ダイアゴナル{lv}"),
            ElementsCode.NtCiSt => new ElementsName($"非接触サーキュラー{lv}"),
            ElementsCode.ChLi1 => new ElementsName("コレオグラフィックダンスリフト"),
            ElementsCode.ChSp1 => new ElementsName("コレオグラフィックスピニングムーブメント"),
            ElementsCode.ChTw1 => new ElementsName("コレオグラフィックツイズリングムーブメント"),
            _ => throw new ArgumentOutOfRangeException(nameof(elementsId.code), elementsId.code, null)
        };
    }
}
